config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :sections
  resources :lessons
  root "courses#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :sections, dependent: :destroy
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :lessons, dependent: :destroy
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    ai_client = AiClient.new
    user_info = " I am a computer science graduate with an ok understanding of core cs fundamentals.
Currently I work as a backend software engineer for about 2 years.My goal is  to gain a deeper understanding of #{course_params[:title].downcase}
from a first principles perspective and gain a better understanding of #{course_params[:title].downcase} for my job as a backend engineer"
    sections_and_lessons = ai_client.generate_course(course_params[:title], course_params[:level], user_info,
                                                     "I prefer to do projects where possible")
    @course = Course.new(title: course_params[:title], level: course_params[:level], goal: user_info)
    sections_and_lessons.each do |section, lessons|
      section_name = section.to_s
      section = @course.sections.build(title:section_name)
      lessons.each do |lesson|
        lesson_name = lesson.to_s
        section.lessons.build(title:lesson_name, content: nil)
      end
    end

    if @course.save
      redirect_to courses_path, notice: "Course created successfully."
    else
      render :new
    end
  end

  def show
    @course = Course.find(params[:id])
    @sections = @course.sections
  end

  def destroy
    if Course.find(params[:id]).destroy
      redirect_to courses_path
    end
  end

  private
  def course_params
    params.require(:course).permit(:level, :title)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    @lesson = Lesson.find(params[:id])
  end

  def edit
    @lesson = Lesson.find(params[:id])
    ai_client = AiClient.new
    @lesson.content = ai_client.generate_lesson(@lesson.section.course.title, @lesson.section.course.level, @lesson.section.course.goal,
                                 @lesson.section.title,@lesson.title)
    @lesson.save
    redirect_to lesson_path(@lesson)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def show
    @section = Section.find(params[:id])
    @lessons = @section.lessons
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLWithRouge < Redcarpet::Render::HTML
    def block_code(code, language)
      language ||= "plaintext"
      formatter = Rouge::Formatters::HTML.new
      lexer = Rouge::Lexer.find_fancy(language, code) || Rouge::Lexers::PlainText
      "<pre class=\"highlight\"><code>#{formatter.format(lexer.lex(code))}</code></pre>"
    end
  end

  def markdown(text)
    renderer = HTMLWithRouge.new(filter_html: true, hard_wrap: true)
    markdown = Redcarpet::Markdown.new(renderer, fenced_code_blocks: true, autolink: true, tables: true)
    markdown.render(text).html_safe
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<%= link_to "New Course", new_course_path %>

<%@courses.each do |course| %>
  <hr>
  <div>
    <%= course.title %>
    <%= course.level %>
    <%= button_to "Delete", course_path(course), method: :delete %>
    <%= button_to "Show", course_path(course), method: :get %>
  </div>
  <hr>
<% end %>

app/views/courses/new.html.erb
<%=form_with(model: @course) do |course| %>
  <div id="course_level_buttons">
    <label>
      <%= course.radio_button :level, "beginner"%> Beginner
    </label>
    <label>
      <%= course.radio_button :level, "intermediate"%> Intermediate
    </label>
    <label>
      <%= course.radio_button :level, "advanced"%> Advanced
    </label>
  </div>
  <div id="course_title_input">
    Topic: <%= course.text_field :title %>
  </div>
  <%=course.submit "Submit" %>
<% end %>

app/views/courses/show.html.erb
<h2><%= @course.title + " - " + @course.level.capitalize%></h2>
<hr>
<div>
  <%@sections.each do |section| %>
    <h3><%=section.title %></h3>
    <%= button_to "Show", section_path(section), method: :get %>
    <%section.lessons.each do |lesson| %>
      <%=lesson.title %>
      <%= button_to "Show", lesson_path(lesson), method: :get %>
      <br>
    <% end %>
    <hr>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Aitutor" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lessons/show.html.erb
<%= @lesson.title %>

<% if @lesson.content.blank? %>
  <%=button_to "Generate lesson", edit_lesson_path(@lesson), method: :get %>
<% else %>
  <%=markdown(@lesson.content) %>
<% end %>

app/views/sections/show.html.erb
<h2><%= @section.title %></h2>
<%@lessons.each do |lesson| %>
  <%= lesson.title %>
  <%= button_to "Show", lesson_path(lesson), method: :get %>
  <br>
<% end %>